import re
import sys
import io
import contextlib
import warnings
from typing import Optional, List, Any, Tuple
from PIL import Image
import streamlit as st
import pandas as pd
import base64
from io import BytesIO

from groq import Groq
from e2b_code_interpreter import Sandbox

warnings.filterwarnings("ignore")

# Extract python code blocks
CODE_BLOCK_PATTERN = re.compile(r"```python\n(.*?)\n```", re.DOTALL)


def extract_python_code(text: str) -> str:
    match = CODE_BLOCK_PATTERN.search(text)
    return match.group(1) if match else ""


def run_code_in_e2b(sandbox: Sandbox, code: str):
    stdout, stderr = io.StringIO(), io.StringIO()

    with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
        execution = sandbox.run_code(code)

    if execution.error:
        st.error("E2B Execution Error")
        st.code(execution.error)
        return None

    return execution.results


def chat_with_llm(
    sandbox: Sandbox,
    user_query: str,
    dataset_path: str,
    df_columns: List[str]
) -> Tuple[Any, str]:

    # 🔒 SCHEMA-AWARE SYSTEM PROMPT (THIS FIXES YOUR ERROR)
    system_prompt = f"""
You are a senior Python data scientist and data visualization expert.

Dataset path: {dataset_path}

Dataset schema:
Columns = {df_columns}

CRITICAL RULES (FOLLOW STRICTLY):
1. Load the CSV using pandas from the given dataset path
2. ALWAYS use the exact column names from the schema above (case-sensitive)
3. NEVER assume column names
4. Use df.columns if needed, but prefer the provided schema
5. Generate Python code for analysis or visualization
6. Wrap ALL Python code inside ```python blocks
7. Use pandas + matplotlib / seaborn / plotly
"""

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_query},
    ]

    client = Groq(api_key=st.session_state.groq_api_key)

    response = client.chat.completions.create(
        model=st.session_state.model_name,
        messages=messages,
        temperature=0.2,
    )

    llm_text = response.choices[0].message.content
    python_code = extract_python_code(llm_text)

    if not python_code:
        st.warning("No Python code generated by the model.")
        return None, llm_text

    results = run_code_in_e2b(sandbox, python_code)
    return results, llm_text


def upload_csv(sandbox: Sandbox, uploaded_file) -> str:
    path = f"./{uploaded_file.name}"
    sandbox.files.write(path, uploaded_file)
    return path


def main():
    st.set_page_config(page_title="AI Data Visualization Agent", layout="wide")
    st.title("📊 AI Data Visualization Agent")
    st.write("Upload a CSV file and ask questions in natural language.")

    # Session state
    st.session_state.setdefault("groq_api_key", "")
    st.session_state.setdefault("e2b_api_key", "")
    st.session_state.setdefault("model_name", "")

    # Sidebar
    with st.sidebar:
        st.header("🔑 Configuration")

        st.session_state.groq_api_key = st.text_input(
            "Groq API Key",
            type="password",
            help="Get from https://console.groq.com/keys",
        )

        st.session_state.e2b_api_key = st.text_input(
            "E2B API Key",
            type="password",
            help="Get from https://e2b.dev",
        )

        model_options = {
            "LLaMA 3.3 70B (Best)": "llama-3.3-70b-versatile",
            "LLaMA 3.1 8B (Fast)": "llama-3.1-8b-instant",
        }

        selected_model = st.selectbox("Select Model", list(model_options.keys()))
        st.session_state.model_name = model_options[selected_model]

    uploaded_file = st.file_uploader("Upload CSV", type="csv")

    if uploaded_file:
        df = pd.read_csv(uploaded_file)

        # Normalize columns defensively (strip whitespace only)
        df.columns = df.columns.str.strip()

        st.subheader("Dataset Preview")
        st.dataframe(df.head())

        st.info(f"Detected Columns: {list(df.columns)}")

        query = st.text_area(
            "Ask a question about your data",
            placeholder="Show a bar chart of Disease vs number of medications",
        )

        if st.button("Analyze"):
            if not st.session_state.groq_api_key or not st.session_state.e2b_api_key:
                st.error("Groq and E2B API keys are required.")
                return

            with Sandbox(api_key=st.session_state.e2b_api_key) as sandbox:
                dataset_path = upload_csv(sandbox, uploaded_file)

                results, explanation = chat_with_llm(
                    sandbox=sandbox,
                    user_query=query,
                    dataset_path=dataset_path,
                    df_columns=list(df.columns),
                )

                st.subheader("🧠 AI Explanation")
                st.write(explanation)

                if results:
                    st.subheader("📊 Output")
                    for r in results:
                        if hasattr(r, "png") and r.png:
                            img = Image.open(BytesIO(base64.b64decode(r.png)))
                            st.image(img)
                        elif hasattr(r, "figure"):
                            st.pyplot(r.figure)
                        elif isinstance(r, (pd.DataFrame, pd.Series)):
                            st.dataframe(r)
                        else:
                            st.write(r)


if __name__ == "__main__":
    main()
